### ISSUE TITLE
ReadMeshChunk: list index out of range

### ISSUE THREAD

**Issue by EliteMasterEric** [Turk645/PokemonMasters#5]
```
Traceback (most recent call last):
  File "C:\Users\eric\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_import_pokemon_masters.py", line 63, in execute
    ReadMeshChunk(CurFile,x,ArmatureObject)
  File "C:\Users\eric\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_import_pokemon_masters.py", line 232, in ReadMeshChunk
    if obj.vertex_groups.find(WeightBoneTable[x[1][i]]) == -1:
IndexError: list index out of range
```

I received this stack tract attempting to import Olivia (`ch0051_00_litchi`) into Blender 2.79b.

**Comment by Turk645** [comment]
Fixed in latest update
