### ISSUE TITLE
Fully importing any model fails since the game's 1.2.0.1459 update

### ISSUE THREAD

**Issue by ghost** [Turk645/PokemonMasters#6]
The plugin manages to import a small part of the model, but then it displays an error.
I did the test with the 1.0.2 (latest) version of the plugin.
```
Traceback (most recent call last):
  File "PokeMas\blender-2.79b-windows64\2.79\scripts\addons\io_import_pokemon_masters.py", line 63, in execute
    ReadMeshChunk(CurFile,x,ArmatureObject)
  File "PokeMas\blender-2.79b-windows64\2.79\scripts\addons\io_import_pokemon_masters.py", line 232, in ReadMeshChunk
    if obj.vertex_groups.find(WeightBoneTable[x[1][i]]) == -1:
IndexError: list index out of range

location: <unknown location>:-1
```

**Comment by Andree12** [comment]
https://github.com/jugolm/PokemonMasters

**Comment by Turk645** [comment]
fixed in latest update
